version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      working_directory: ~/CVDS_LAB6/PrimeFaces
      - maven/test # checkout, build, test, and upload test results
