version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  heroku: circleci/heroku@1.2.2

#executors:
  #working_directory: ~/project/PrimeFaces

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          app_src_directory: PrimeFaces
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
